#cloud-config
autoinstall:
  version: 1
  variables:
    ServerName: landscape
  apt:
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        - default
        uri: http://archive.ubuntu.com/ubuntu/
      sources:
        landscape:
          source: ppa:landscape/self-hosted-24.04
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: landscape
    password: $6$RycIl1LwdIHXoBIM$q4U9MgvHZCR.KJeeocDVlT2gUkawZRNIMYtTecEg9AYL2sSMv.1TRJTQbs0IoeL.PfFiomhR0dtFySfwoeIC61
    realname: Jerry Carter
    username: jerry
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eth0:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  package_update: true
  package_upgrade: true
  packages:
    - net-tools
    - git
    - ansible
  ansible:
    package_name: ansible-core
    pull: 
      url: https://github.com/hayabusajerry/LndScpAns.git
      playbook_name: lndscpserverinst.yaml
  
  ssh:
    allow-pw: true
    authorized-keys: [ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIArpnnfDHsgNxEVVjQa2jsqdwqpo7WajcDaU8VHGMmZuECsyU2X1+vdavoK8PObGFaoPeI5yLLiDWCKdPEMsg9s5JBui05tevHwmGBqDxTBf3RJui5J9bpV+V8XLIiYSGbdxDzc74Ue9e65iU6Z+GedWjrUYlysKit5dlD/m/y8cneP68Bf+sIMVrOvWTu3x5H5FHs0hmZQ5XTYh1arsLWqfy1CWtfNsNBT4CfypfUWe9mf0hXX5rRWgDV5PmnsOMwv5c8Lp3RyM/pleKDRSiP/v1ilMOkJsRCJ56ptOP6rOhNwgxF7dw5oamn1llXXhbHGUEBfNIib1yGBsJnDcfrejRubbexledLBcEyzhFMsCOntesVNRZtR+fmFnU76hPyR1R3CTdcZjNiIWEA63EWP87V+9w/zUFq+Ldzmv0ClzkngenfNERQ/zdJikQIzYFCf7FSw3QKC0qsi0/C7LHBZSeFd0LeaolURYyBuaCK+r2+WP2aBCYfdfD9+UpWK8= jerry@rafiki]
    install-server: true
  storage:
    layout:
      name: lvm
  updates: security
  user-data:
    runcmd:
        - sudo hostnamectl set-hostname "landscape.perseus-it.lan" 
        - sudo apt install -y realmd libnss-sss libpam-sss sssd sssd-tools adcli samba-common-bin oddjob oddjob-mkhomedir packagekit
        ##- sudo systemctl disable systemd-resolved.service 
        ##- sudo systemctl stop systemd-resolved.service
        ##-  echo Bandit1200! | sudo realm join -U jerryad --client-software=sssd  perseus-it.lan
        ##- sudo realm permit -g "Domain Users"@perseus-it.lan
        ##- sudo sed -i -e 's/use_fully_qualified_names = True/use_fully_qualified_names = False/g' /etc/sssd/sssd.conf
        ##- sudo apt install -y ca-certificates software-properties-common
        - export HOST_NAME=landscape; export DOMAIN=perseus-it.lan; export FQDN=$HOST_NAME.$DOMAIN
        - sudo add-apt-repository -y ppa:landscape/self-hosted-24.04
        ##- sudo DEBIAN_FRONTEND=noninteractive apt-get install -y landscape-server-quickstart
        ##- sudo snap install certbot --classic
        ##- sudo certbot --apache --non-interactive --no-redirect --agree-tos --email jerry.carter@perseus-it.com --domains landscape.perseus-it.lan
        - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=AU/ST=Western Australia/L=Perth/O=Perseus-it/OU=IT/CN=landscape.perseus-it.lan/emailAddress=jerry.carter@perseus-it.com"
        ##- sudo apt install -y landscape-client
        ##- export LANDSCAPE_ACCOUNT_NAME=standalone; export LANDSCAPE_FQDN=landscape.perseus-it.lan; export LANDSCAPE_COMPUTER_TITLE=LANDSCAPE; sudo landscape-config --silent --account-name="${LANDSCAPE_ACCOUNT_NAME}" --computer-title="${LANDSCAPE_COMPUTER_TITLE}" --tags='' --script-users='nobody,landscape,root' --ping-url="http://${LANDSCAPE_FQDN}/ping" --url="https://${LANDSCAPE_FQDN}/message-system"