#cloud-config
autoinstall:
  version: 1
  apt:
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        - default
        uri: http://archive.ubuntu.com/ubuntu/
    sources:
      landscape:
        source: ppa:landscape/self-hosted-24.04
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: landscape
    password: $6$RycIl1LwdIHXoBIM$q4U9MgvHZCR.KJeeocDVlT2gUkawZRNIMYtTecEg9AYL2sSMv.1TRJTQbs0IoeL.PfFiomhR0dtFySfwoeIC61
    realname: Nopsema Admin
    username: nopsema
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_AU.UTF-8
  network:
    ethernets:
      eth0:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  package_update: true
  package_upgrade: true
  packages:
    - net-tools
    - git
    - ansible
    - linux-virtual
    - linux-cloud-tools-virtual
    - linux-tools-virtual 
  
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true

  storage:
    config:

      - id: disk-data
        type: disk
        match:
          size: largest
        grub_device: false
        wipe: superblock-recursive

      - id: vg1-data
        devices:
        - disk-data
        name: vg1-data
        type: lvm_volgroup

      - id: lv1-data
        volgroup: vg1-data
        name: lv1-data
        size: -1
        type: lvm_partition

      - id: disk-os
        type: disk
        match:
          size: smallest
        ptable: gpt
        grub_device: true
        wipe: superblock-recursive

      - id: bios
        type: partition
        partition_type: 21686148-6449-6e6f-744e-656564454649
        device: disk-os
        size: 1048576
        flag: bios_grub
        offset: 1048576
        grub_device: false

      - id: bootpart
        type: partition
        device: disk-os
        size: 1G

      - id: pvpart
        type: partition
        device: disk-os
        size: -1

      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices: 
        - pvpart

      - id: root_lv
        type: lvm_partition
        name: root_lv
        volgroup: vg0
        size: 50G

      - id: lv1-data_fs
        type: format
        volume: lv1-data
        fstype: ext4      

      - id: bootpart_fs
        type: format
        volume: bootpart
        fstype: ext4

      - id: root_lv_fs
        type: format
        volume: root_lv
        fstype: ext4

      - id: root_lv_mount
        type: mount
        device: root_lv_fs
        path: /

      - id: bootpart-mount
        type: mount
        device: bootpart_fs
        path: /boot

      - id: lv1-data-mount
        type: mount
        device: lv1-data_fs
        path: /var/lib/landscape/landscape-repository

  updates: security

  user-data:
    runcmd:
        - sudo hostnamectl set-hostname "landscape.nopsema.gov.au" 
        - sudo apt install -y realmd libnss-sss libpam-sss sssd sssd-tools adcli samba-common-bin oddjob oddjob-mkhomedir policykit-1 packagekit
        - echo Bandit1200! | sudo realm join -U jerryad --client-software=sssd  nopsema.gov.au
        - sudo realm permit -g "Domain Users"@nopsema.gov.au
        - sudo sed -i -e 's/use_fully_qualified_names = True/use_fully_qualified_names = False/g' /etc/sssd/sssd.conf
        - sudo sed  -i -e '$a\'$'\n''session optional        pam_mkhomedir.so skel=/etc/skel umask=077' /etc/pam.d/common-session
        - sudo apt install -y ca-certificates software-properties-common
        - export HOST_NAME=landscape; export DOMAIN=nopsema.gov.au; export FQDN=$HOST_NAME.$DOMAIN
        - sudo add-apt-repository -y ppa:landscape/self-hosted-24.04
        - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y landscape-server-quickstart
        - sudo snap install landscape-api
        - sudo snap install certbot --classic
        ##- sudo certbot --apache --non-interactive --no-redirect --agree-tos --email jerry.carter@perseus-it.com --domains landscape.nopsema.gov.au
        - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=AU/ST=Western Australia/L=Perth/O=Perseus-it/OU=IT/CN=landscape.nopsema.gov.au/emailAddress=jerry.carter@perseus-it.com"
        - sudo apt install -y landscape-client
        - export LANDSCAPE_ACCOUNT_NAME=standalone; export LANDSCAPE_FQDN=landscape.nopsema.gov.au; export LANDSCAPE_COMPUTER_TITLE=LANDSCAPE; sudo landscape-config --silent --account-name="${LANDSCAPE_ACCOUNT_NAME}" --computer-title="${LANDSCAPE_COMPUTER_TITLE}" --tags='' --script-users='nobody,landscape,root' --ping-url="http://${LANDSCAPE_FQDN}/ping" --url="https://${LANDSCAPE_FQDN}/message-system"